###
POST http://127.0.0.1:3000/api/user/signup
content-type: application/json

{
  "userName" : "유저", 
  "password" : "user2", 
  "email" : "user2@gmail.com", 
  "phone" : "010-1234-1234", 
  "address" : "서울",
  "userType" : "0"
}

###
POST http://127.0.0.1:3000/api/user/login
content-type: application/json

{
  "email" : "user@gmail.com",
  "password" : "user"
}

###
GET http://127.0.0.1:3000/api/user/list
content-type: application/json; charset=UTF-8
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiaWF0IjoxNjgzNzQ4MzMzLCJleHAiOjE2ODM3NDgzMzR9.tVxPHLBemrx_E0cTGjwXoZ7-k0ynhk6PBKbVymZAfQw
Refresh : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2ODM3NDgzMzMsImV4cCI6MTY4MzgzNDczM30.JIlIdm-SIGetiUEipV60lnX0QaKo1Px7UA_PM_WaKi8
