post http://localhost:3000/signup
Content-Type: application/json 

{
  "email":"kjk23",
  "password":"qwe123",
  "userName":"kihan",
  "phone":"123123890",
  "address": "suwondsadf",
  "userType": 3,
  "confirm":"qwe123"
}
