GET http://localhost:3000/api/user/list

###

DELETE  http://localhost:3000/api/admin/2

###

GET http://localhost:3000/api/admin/orderList

###

GET http://localhost:3000/api/admin/orderDone

###

GET http://localhost:3000/api/admin/itemList

###
POST http://localhost:3000/api/admin
Content-Type: application/json; charset=UTF-8

{
      "menuName" : "간장양념",
      "menuPrice" : "24000"
}


###

POST http://localhost:3000/api/user/signup
Content-Type: application/json; charset=UTF-8

{
      "userName": "영환",
      "password": "12341234",
      "email": "wjdrl@gmail.com",
      "phone": "010-4449-0673",
      "address": "강서구 서구 서구다",
      "userType": 2
}

###

POST http://localhost:3000/api/user/login
Content-Type: application/json; charset=UTF-8

{
      "email": "dudg622@gmail.com",
      "password": "12341234"
}

###
PUT http://localhost:3000/api/user
Content-Type: application/json; charset=UTF-8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNjc2NjI1NjEwfQ.RA6tCHLDSP7EgeovLgrZGnfEKJ7GUKg_lXi1ZOnF1V8;


{
      "password": "12341234",
      "address": "서울남남남남",
      "phone": "010-1232-3232"
}

###
DELETE http://localhost:3000/api/user/100
Content-Type: application/json; charset=UTF-8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNjc2NjI1NjEwfQ.RA6tCHLDSP7EgeovLgrZGnfEKJ7GUKg_lXi1ZOnF1V8;

